

[music_0]
track_name = "Doki Doki Literature Club!"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = ""
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 129.79545455 loop 20.70454545>bgm/1.ogg"
track_fadeout = "0"
length = "241.3365"

[music_1]
track_name = "Ohayou Sayori!"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = ""
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 80.9579646 loop 4.49778761>bgm/2.ogg"
track_fadeout = "0"
length = "163.175"

[music_2]
track_name = "Dreams of Love and Literature"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = ""
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 122.65 loop 19.45>bgm/4.ogg"
track_fadeout = "0"
length = "250.157"

[music_3]
track_name = "Okay, Everyone!"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_okayeveryone"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 91.6136364 loop 4.34090909>bgm/5.ogg"
track_fadeout = "0"
length = "184.796"

[music_4]
track_name = "Play With Me"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_playwithme"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 86.1590909 loop 6.52272727>bgm/6.ogg"
track_fadeout = "0"
length = "173.884"

[music_5]
track_name = "Poem Panic!"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_poempanic"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 71.4364407 loop 2.28389831>bgm/7.ogg"
track_fadeout = "0"
length = "148.559"

[music_6]
track_name = "Daijoubu!"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_daijoubu"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 96.0564516 loop 13.4758065>bgm/8.ogg"
track_fadeout = "0"
length = "185.752"

[music_7]
track_name = "My Feelings"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_myfeelings"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 70.25 loop 13.5833333>bgm/9.ogg"
track_fadeout = "0"
length = "123.583"

[music_8]
track_name = "My Confession"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_myconfession"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 105.615854 loop 17.2621951>bgm/10.ogg"
track_fadeout = "0"
length = "186.96"

[music_9]
track_name = "Sayo-nara"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_sayonara"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 92.9032258 loop 30.9677419>bgm/d-ost.ogg"
track_fadeout = "0"
length = "157.199"

[music_10]
track_name = "Just Monika."
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_justmonika"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 192.65 loop 0.65>bgm/m1a.ogg"
track_fadeout = "0"
length = "202.675"

[music_11]
track_name = "I Still Love You"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_istillloveyou"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 70.55 loop 19.35>bgm/monika-end.ogg"
track_fadeout = "0"
length = "163.934"

[music_12]
track_name = "Your Reality"
artist = "Dan Salvato"
asset_bundle = "jukebox_images"
asset_name = "ddlc ost cover"
unlock_show = "bgm_yourreality"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<loop 0.0>bgm/credits.ogg"
track_fadeout = "0"
length = "181.7202"

[music_13]
track_name = "My Song, Your Note"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_mysongyournote"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 123.75 loop 75.75>bgm/DLCP_bgm/p1.ogg"
track_fadeout = "0"
length = "163.2891"

[music_14]
track_name = "Peachy Pie"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_peachypie"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 66.285714 loop 11.4285714>bgm/DLCP_bgm/p2.ogg"
track_fadeout = "0"
length = "129.1729"

[music_15]
track_name = "Strawberry Peppermint"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_strawberrypeppermint"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 100.909091 loop 11.4285714>bgm/DLCP_bgm/p3.ogg"
track_fadeout = "0"
length = "189.5688"

[music_16]
track_name = "Lavender Mist"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_lavendermist"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 97.8 loop 30.6>bgm/DLCP_bgm/p4.ogg"
track_fadeout = "0"
length = "160.254"

[music_17]
track_name = "Just a Little Bit"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_justalittlebit"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 82 loop 18>bgm/DLCP_bgm/p5.ogg"
track_fadeout = "0"
length = "147.9923"

[music_18]
track_name = "Let's Teamwork!"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_letsteamwork"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 67.6363636 loop 24>bgm/DLCP_bgm/p6.ogg"
track_fadeout = "0"
length = "118.4068"

[music_19]
track_name = "Dusk"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_dusk"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "bgm/DLCP_bgm/p7.ogg"
track_fadeout = "0"
length = "101.5662"

[music_20]
track_name = "Piece by Piece"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_piecebypiece"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 74 loop 10>bgm/DLCP_bgm/p8.ogg"
track_fadeout = "0"
length = "141.5521"

[music_21]
track_name = "Hug Energy"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_hugenergy"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "<to 112.5 loop 22.5>bgm/DLCP_bgm/p9.ogg"
track_fadeout = "0"
length = "186.9141"

[music_22]
track_name = "Stories of Friendship and Literature"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_sofal"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "bgm/DLCP_bgm/p10.ogg"
track_fadeout = "0"
length = "148.7917"

[music_23]
track_name = "My Song, Your Note (Piano)"
artist = "Varien"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "bgm_mysongyournotepiano"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "bgm/DLCP_bgm/p1-piano.ogg"
track_fadeout = "0"
length = "93.008"

[music_24]
track_name = "Candy Hearts (feat. Jason Hayes)"
artist = "Jason Hayes"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = ""
unlock_hide = "act_2;candy_heartz_first"
unlock_reshow = "candy_heartz"
unlock_trigger = "candy_heartz_first"
loop_count = "0"
track_definition = "bgm/Candy_Hearts.ogg"
track_fadeout = "0"
length = "175.6535"

[music_25]
track_name = "Candy Hearts (feat. Jason Hayes)"
artist = "Jason Hayes"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "act_2;candy_heartz_first"
unlock_hide = "candy_heartz"
unlock_reshow = ""
unlock_trigger = "candy_heartz"
loop_count = "0"
track_definition = "bgm/Candy_Heartz_First_Time.ogg"
track_fadeout = "0"
length = "67.49821"

[music_26]
track_name = "Candy Heartz (feat. Jason Hayes)"
artist = "Jason Hayes"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = "candy_heartz"
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "bgm/Candy_Heartz.ogg"
track_fadeout = "0"
length = "59.99873"

[music_27]
track_name = "Dear Sunshine (feat. Azuria Sky)"
artist = "Azuria Sky"
asset_bundle = "jukebox_images"
asset_name = "ddlc plus ost cover"
unlock_show = ""
unlock_hide = ""
unlock_reshow = ""
unlock_trigger = ""
loop_count = "0"
track_definition = "bgm/DLCP_bgm/11_Dear_Sunshine_Bonus.ogg"
track_fadeout = "0"
length = "235.579"